server:
  port: 9001
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mantou?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: moha-users
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  scan:
    base-packages: com.moha.users.servce
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: moha-books
